export {default as HomePage} from './Home/HomePage';
export {default as ProductsList} from './Products/ProductsList';
export {default as ProductDetails} from './ProductDetails';
export {default as Login} from './Login';
export {default as Register} from './Register';
export {default as DashboardPage} from './Dashboard/DashboardPage';
export {default as CartPage} from './Cart/CartPage'
export {default as OrderPage} from './Order/OrderPage'
export {default as PageNotFound} from './PageNotFound'